"""add embedding and reranking provider names to Message

Revision ID: 62623851660c
Revises: 0abab5e6f825
Create Date: 2026-06-17 15:03:22.517611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62623851660c'
down_revision: Union[str, Sequence[str], None] = '0abab5e6f825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('retrieval_embedding_provider', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('retrieval_reranking_provider', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'retrieval_reranking_provider')
    op.drop_column('messages', 'retrieval_embedding_provider')
    # ### end Alembic commands ###
