"""Message store route plan fields

Revision ID: 82bbb3552efc
Revises: bce67f0c9bd7
Create Date: 2026-06-05 12:30:40.634045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82bbb3552efc'
down_revision: Union[str, Sequence[str], None] = 'bce67f0c9bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

route_intent_enum = sa.Enum('ANSWER', 'SEARCH', 'COMPARE', 'ACTION', 'CLARIFY', name='route_intent', create_type=False)
route_retrieval_scope_enum = sa.Enum('NONE', 'INTERNAL', 'PUBLIC', 'MIXED', name='route_retrieval_scope', create_type=False)
route_tool_action_enum = sa.Enum('NONE', 'CREATE_TICKET', 'SEND_EMAIL', 'SCHEDULE_EVENT', 'UPLOAD_DOCUMENT', 'RUN_JOB', 
                                 'CALL_API', 'MODIFY_DATABASE', 'OTHER', name='route_tool_action', create_type=False)
route_response_mode_enum = sa.Enum('DIRECT_ANSWER', 'RAG_ANSWER', 'SEARCH_RESULTS', 'COMPARISON', 'TOOL_WITH_CONTEXT', 
                                   'TOOL_ONLY', 'ASK_CLARIFYING_QUESTION', name='route_response_mode', create_type=False)
llm_route_enum = postgresql.ENUM(
    "DIRECT",
    "RAG",
    "CLARIFY",
    "TOOL",
    name="llm_route",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # PostgreSQL enum types must exist before a column can use them.
    route_intent_enum.create(bind, checkfirst=True)
    route_retrieval_scope_enum.create(bind, checkfirst=True)
    route_tool_action_enum.create(bind, checkfirst=True)
    route_response_mode_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('route_intent', route_intent_enum, nullable=True))
    op.add_column('messages', sa.Column('route_retrieval_scope', route_retrieval_scope_enum, nullable=True))
    op.add_column('messages', sa.Column('route_tool_action', route_tool_action_enum, nullable=True))
    op.add_column('messages', sa.Column('route_response_mode', route_response_mode_enum, nullable=True))
    op.add_column('messages', sa.Column('route_confidence', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('route_plan', sa.JSON(), nullable=True))
    op.drop_column('messages', 'route')
    # ### end Alembic commands ###

    llm_route_enum.drop(bind, checkfirst=True)


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    llm_route_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column("route", llm_route_enum, nullable=True))
    op.drop_column('messages', 'route_plan')
    op.drop_column('messages', 'route_confidence')
    op.drop_column('messages', 'route_response_mode')
    op.drop_column('messages', 'route_tool_action')
    op.drop_column('messages', 'route_retrieval_scope')
    op.drop_column('messages', 'route_intent')
    # ### end Alembic commands ###

    # Drop the enum type after no columns depend on it.
    route_intent_enum.drop(bind, checkfirst=True)
    route_retrieval_scope_enum.drop(bind, checkfirst=True)
    route_tool_action_enum.drop(bind, checkfirst=True)
    route_response_mode_enum.drop(bind, checkfirst=True)
