"""add metadata fields to Message

Revision ID: bce67f0c9bd7
Revises: ae21d50cbaa0
Create Date: 2026-06-03 12:50:10.670875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce67f0c9bd7'
down_revision: Union[str, Sequence[str], None] = 'ae21d50cbaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('route', sa.Enum('DIRECT', 'RAG', 'CLARIFY', 'TOOL', name='llm_route'), nullable=True))
    op.add_column('messages', sa.Column('finish_reason', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('retrieval_embedding_model', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('retrieval_reranking_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'retrieval_reranking_model')
    op.drop_column('messages', 'retrieval_embedding_model')
    op.drop_column('messages', 'total_tokens')
    op.drop_column('messages', 'completion_tokens')
    op.drop_column('messages', 'prompt_tokens')
    op.drop_column('messages', 'finish_reason')
    op.drop_column('messages', 'route')
    op.drop_column('messages', 'model')
    # ### end Alembic commands ###
