"""add content_tokens to Message

Revision ID: fc158a72e6d0
Revises: 82bbb3552efc
Create Date: 2026-06-05 14:36:47.150763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc158a72e6d0'
down_revision: Union[str, Sequence[str], None] = '82bbb3552efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'content_tokens')
    # ### end Alembic commands ###
